"""Dashboard constants — immutable configuration and lookup tables."""
from datetime import timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

BASE_DIR = Path(__file__).resolve().parent.parent.parent  # project root
HTML_PATH = BASE_DIR / "web" / "orders_dashboard.html"
COSTS_HTML_PATH = BASE_DIR / "web" / "finance_costs.html"
PALLETIZATION_WEB_DIR = BASE_DIR / "web" / "palletization"
MSK = timezone(timedelta(hours=3))
SUPPLY_ACCEPTANCE_CACHE: Dict[str, Dict[str, Any]] = {}
SUPPLY_ACCEPTANCE_CACHE_MAX_ENTRIES = 30

SUPPLY_CLUSTER_MARKUP_DEFAULTS: List[Tuple[str, float]] = [
    ("Оренбург", 8.0),
    ("Пермь", 8.0),
    ("Омск", 8.0),
    ("Саратов", 8.0),
    ("Москва, МО и Дальние регионы", 8.0),
    ("Санкт-Петербург и СЗО", 8.0),
    ("Самара", 8.0),
    ("Ярославль", 0.0),
    ("Махачкала", 8.0),
    ("Невинномысск", 8.0),
    ("Красноярск", 0.0),
    ("Краснодар", 8.0),
    ("Тверь", 8.0),
    ("Воронеж", 4.0),
    ("Екатеринбург", 8.0),
    ("Уфа", 8.0),
    ("Тюмень", 8.0),
    ("Ростов", 0.0),
    ("Казань", 8.0),
    ("Калининград", 8.0),
    ("Новосибирск", 0.0),
    ("Дальний Восток", 8.0),
    ("Алматы", 6.0),
    ("Астана", 6.0),
    ("Беларусь", 6.0),
    ("Армения", 0.0),
    ("Азербайджан", 0.0),
    ("Грузия", 0.0),
    ("Кыргызстан", 0.0),
    ("Узбекистан", 0.0),
]
SUPPLY_MACROLOCAL_CLUSTER_FALLBACKS: Dict[str, int] = {
    "москва, мо и дальние регионы": 4039,
    "москва и мо": 4039,
    "санкт петербург и сзо": 4007,
    "санкт петербург": 4007,
    "казань": 4041,
    "краснодар": 4065,
    "красноярск": 4043,
    "новосибирск": 4067,
    "екатеринбург": 4066,
    "самара": 4042,
    "саратов": 4049,
    "уфа": 4040,
    "ярославль": 4051,
    "тверь": 4072,
    "воронеж": 4036,
    "пермь": 4070,
    "омск": 4068,
    "оренбург": 4069,
    "ростов": 4071,
    "тюмень": 4046,
    "дальний восток": 4002,
    "калининград": 4004,
    "махачкала": 4077,
    "невинномысск": 4076,
}


PLAN_BASELINE_REVENUE = 6_000_000.0
PLAN_BASE_VALUES = {
    "revenue_mp": 6_000_000.0,
    "expenses_mp": 2_681_151.0,
    "marketing": 500_872.0,
    "expenses_total": 3_182_023.0,
    "money_on_account": 2_460_000.0,
    "material_cost": 293_759.0,
    "gross_profit": 1_800_000.0,
}
PLAN_BASE_PCTS = {
    "expenses_mp_pct": 0.4469,
    "marketing_pct": 0.08,
    "expenses_total_pct": 0.59,
    "gross_to_money_pct": 0.7317,
    "gross_to_revenue_pct": 0.30,
}


FINANCE_REPORT_ROWS = [
    {"key": "ozon", "label": "Озон", "kind": "section"},
    {"key": "revenue_plan", "label": "Выручка план", "kind": "value"},
    {"key": "revenue_cumulative", "label": "Выручка накопительно", "kind": "derived"},
    {"key": "ordered_units", "label": "Продано", "kind": "value"},
    {"key": "returned_units", "label": "Возвраты", "kind": "value"},
    {"key": "returns_pct", "label": "Возвраты %", "kind": "derived", "format": "percent"},
    {"key": "revenue_sales", "label": "Выручка / продажи - возвраты", "kind": "derived"},
    {"key": "client_revenue", "label": "Оплачено клиентом (факт)", "kind": "derived"},
    {"key": "sales_total", "label": "Продажи", "kind": "derived"},
    {"key": "revenue", "label": "Выручка", "kind": "value"},
    {"key": "sales_discount_points", "label": "Баллы за скидки", "kind": "value"},
    {"key": "sales_partner_programs", "label": "Программы партнёров", "kind": "value"},
    {"key": "returns_total", "label": "Возвраты", "kind": "derived"},
    {"key": "returns_revenue", "label": "Возврат выручки", "kind": "value"},
    {"key": "returns_discount_points", "label": "Баллы за скидки", "kind": "value"},
    {"key": "returns_partner_programs", "label": "Программы партнёров", "kind": "value"},
    {"key": "ozon_fee_total", "label": "Вознаграждение Ozon", "kind": "value"},
    {"key": "sale_commission", "label": "Вознаграждение за продажу", "kind": "value"},
    {"key": "return_commission", "label": "Возврат вознаграждения", "kind": "value"},
    {"key": "delivery_services_total", "label": "Услуги доставки", "kind": "value"},
    {"key": "dropoff_processing", "label": "Обработка отправления Drop-off", "kind": "value"},
    {"key": "reverse_logistics", "label": "Обратная логистика", "kind": "value"},
    {"key": "logistics", "label": "Логистика", "kind": "value"},
    {"key": "courier_departure", "label": "Организация выезда курьера", "kind": "value"},
    {"key": "pickup_courier_delivery", "label": "Доставка курьером Pick-up", "kind": "value"},
    {"key": "pickup_processing", "label": "Обработка отправления Pick-up", "kind": "value"},
    {"key": "agent_services_total", "label": "Услуги партнёров", "kind": "value"},
    {"key": "star_products", "label": "Страхование товара от массовых повреждений", "kind": "value"},
    {"key": "delivery_to_pickup", "label": "Доставка до места выдачи", "kind": "value"},
    {"key": "partner_returns_processing", "label": "Обработка возвратов, отмен и невыкупов партнёрами", "kind": "value"},
    {"key": "acquiring", "label": "Эквайринг", "kind": "value"},
    {"key": "partner_dropoff_processing", "label": "Обработка отправления Drop-off партнёрами", "kind": "value"},
    {"key": "partner_packaging", "label": "Упаковка товара партнёрами", "kind": "value"},
    {"key": "temporary_partner_storage", "label": "Временное размещение товара партнёрами", "kind": "value"},
    {"key": "fbo_services_total", "label": "Услуги FBO", "kind": "value"},
    {"key": "fbo_acceptance_services", "label": "Услуги приемки", "kind": "derived"},
    {"key": "fbo_cargo_processing", "label": "Обработка товара в составе грузоместа", "kind": "derived"},
    {"key": "piece_acceptance", "label": "Обработка товара в составе грузоместа: Поштучная приёмка", "kind": "value"},
    {"key": "zone_sorting", "label": "Обработка товара в составе грузоместа: Сортировка по зонам размещения", "kind": "value"},
    {"key": "excess_processing", "label": "Обработка опознанных излишков в составе грузоместа", "kind": "value"},
    {"key": "fbo_booking_slot_staff", "label": "Бронирование места и персонала для поставки с неполным составом", "kind": "value"},
    {"key": "fbo_delivery_to_warehouse", "label": "Доставка до склада", "kind": "derived"},
    {"key": "cross_docking", "label": "Кросс-докинг", "kind": "value"},
    {"key": "fbo_storage_services", "label": "Складские услуги", "kind": "derived"},
    {"key": "warehouse_placement", "label": "Размещение товаров на складах Ozon", "kind": "value"},
    {"key": "valid_preparation", "label": "Подготовка товара к вывозу", "kind": "value"},
    {"key": "ozon_delivery_to_pvz", "label": "Вывоз товара со склада силами Ozon", "kind": "value"},
    {"key": "promotion_total", "label": "Реклама (НАЧ)", "kind": "value"},
    {"key": "ad_spend", "label": "Реклама", "kind": "value"},
    {"key": "review_points", "label": "Баллы за отзывы", "kind": "value"},
    {"key": "review_pin", "label": "Продвижение с оплатой за заказ", "kind": "value"},
    {"key": "accelerated_reviews", "label": "Ускоренный сбор отзывов", "kind": "value"},
    {"key": "pay_per_click", "label": "Оплата за клик", "kind": "value"},
    {"key": "premium_plus_subscription", "label": "Подписка Premium Plus", "kind": "value"},
    {"key": "other_services", "label": "Другие услуги и штрафы", "kind": "derived"},
    {"key": "penalties_total", "label": "Штрафы", "kind": "derived"},
    {"key": "penalty_non_recommended_slot", "label": "Отгрузка в нерекомендованный слот", "kind": "value"},
    {"key": "loans_factoring", "label": "Займы и факторинг", "kind": "value"},
    {"key": "other_accrual_adjustments", "label": "Прочие начисления - Корректировка стоимости услуг", "kind": "value"},
    {"key": "shortage_retention", "label": "Удержание за недовложение товара", "kind": "value"},
    {"key": "other_services_misc", "label": "Другие услуги", "kind": "derived"},
    {"key": "utilization", "label": "Утилизация товара", "kind": "value"},
    {"key": "packaging_materials", "label": "Обеспечение материалами для упаковки товара", "kind": "value"},
    {"key": "operational_errors", "label": "Обработка операционных ошибок продавца", "kind": "value"},
    {"key": "temporary_sc_storage", "label": "Временное размещение товара в СЦ/ПВЗ", "kind": "value"},
    {"key": "all_expenses", "label": "Расходы маркетплейса (все)", "kind": "derived"},
    {"key": "compensations", "label": "Компенсации и декомпенсации", "kind": "value"},
    {"key": "marketplace_expenses", "label": "Расходы МП", "kind": "derived"},
    {"key": "marketplace_expenses_pct", "label": "Расходы МП, %", "kind": "derived", "format": "percent"},
    {"key": "marketing_pct", "label": "Маркетинг, %", "kind": "derived", "format": "percent"},
    {"key": "accrued", "label": "Начислено", "kind": "derived"},
    {"key": "material_cost", "label": "Себестоимость - возвраты", "kind": "value"},
    {"key": "gross_profit", "label": "Валовая прибыль", "kind": "derived"},
    {"key": "gross_profit_pct_oz", "label": "Валовая прибыль, % к OZ", "kind": "derived", "format": "percent"},
    {"key": "gross_profit_pct_accrued", "label": "Валовая прибыль, % к РС", "kind": "derived", "format": "percent"},
    {"key": "gross_profit_cumulative", "label": "Валовая накопительно", "kind": "derived"},
    {"key": "gross_profit_plan", "label": "Валовая план", "kind": "derived"},
]

FINANCE_ROW_META = {row["key"]: row for row in FINANCE_REPORT_ROWS}
FINANCE_ZERO_ROWS = [
    "revenue_plan",
    "sales_discount_points",
    "sales_partner_programs",
    "returns_discount_points",
    "returns_partner_programs",
    "pickup_processing",
    "courier_departure",
    "dropoff_processing",
    "logistics",
    "reverse_logistics",
    "pickup_courier_delivery",
    "partner_returns_processing",
    "star_products",
    "temporary_partner_storage",
    "partner_dropoff_processing",
    "partner_packaging",
    "delivery_to_pickup",
    "acquiring",
    "cross_docking",
    "fbo_booking_slot_staff",
    "valid_preparation",
    "ozon_delivery_to_pvz",
    "warehouse_placement",
    "piece_acceptance",
    "zone_sorting",
    "excess_processing",
    "premium_plus_subscription",
    "pay_per_click",
    "review_points",
    "review_pin",
    "accelerated_reviews",
    "penalty_non_recommended_slot",
    "packaging_materials",
    "operational_errors",
    "temporary_sc_storage",
    "utilization",
    "loans_factoring",
    "other_accrual_adjustments",
    "shortage_retention",
    "compensations",
    "material_cost",
]

FINANCE_DESCRIPTION_FILTERS = {
    "ordered_units": ["заказано"],
    "returned_units": ["Возвраты"],
    "revenue": ["Выручка"],
    "sales_discount_points": ["Баллы за скидки"],
    "sales_partner_programs": ["Программы партнёров"],
    "returns_revenue": ["Возврат выручки"],
    "returns_discount_points": ["Баллы за скидки (возврат)"],
    "returns_partner_programs": ["Программы партнёров (возврат)"],
    "sale_commission": ["Вознаграждение за продажу"],
    "return_commission": ["Возврат вознаграждения"],
    "pickup_processing": ["Обработка отправления Pick-up"],
    "courier_departure": ["Организация выезда курьера"],
    "dropoff_processing": ["Обработка отправления Drop-off"],
    "logistics": ["Логистика"],
    "reverse_logistics": ["Обратная логистика"],
    "pickup_courier_delivery": ["Доставка курьером Pick-up"],
    "partner_returns_processing": ["Обработка возвратов, отмен и невыкупов партнёрами"],
    "star_products": ["Звёздные товары", "Страхование товара от массовых повреждений"],
    "temporary_partner_storage": ["Временное размещение товара партнерами", "Временное размещение товара партнёрами"],
    "partner_dropoff_processing": ["Обработка отправления Drop-off партнёрами (АПВЗ)", "Обработка отправления Drop-off партнёрами"],
    "partner_packaging": ["Упаковка товара партнёрами"],
    "delivery_to_pickup": ["Доставка до места выдачи"],
    "acquiring": ["Эквайринг"],
    "cross_docking": ["Кросс-докинг"],
    "valid_preparation": ["Подготовка товара к вывозу: Валид", "Подготовка товара к вывозу"],
    "ozon_delivery_to_pvz": ["Вывоз товара со склада силами Ozon: Доставка до ПВЗ", "Вывоз товара со склада силами Ozon"],
    "warehouse_placement": ["Размещение товаров на складах Ozon"],
    "piece_acceptance": ["Обработка товара в составе грузоместа: Поштучная приёмка"],
    "zone_sorting": ["Обработка товара в составе грузоместа: Сортировка по зонам размещения"],
    "excess_processing": ["Обработка опознанных излишков в составе грузоместа"],
    "premium_plus_subscription": ["Подписка Premium Plus"],
    "pay_per_click": ["Оплата за клик"],
    "review_points": ["Баллы за отзыв", "Баллы за отзывы"],
    "review_pin": ["Закрепление отзыва", "Продвижение с оплатой за заказ"],
    "accelerated_reviews": ["Ускоренный сбор отзывов"],
    "penalty_non_recommended_slot": ["Отгрузка в нерекомендованный слот"],
    "packaging_materials": ["Обеспечение материалами для упаковки товара"],
    "operational_errors": [
        "Обработка операционных ошибок продавца",
        "Жалобы покупателей: привезли не тот товар",
    ],
    "temporary_sc_storage": ["Временное размещение товара в СЦ/ПВЗ"],
    "utilization": ["Утилизация товаров", "Утилизация товара"],
    "loans_factoring": ["Займы и факторинг"],
    "other_accrual_adjustments": ["Прочие начисления - Корректировка стоимости услуг"],
    "shortage_retention": ["Удержание за недовложение товара"],
    "compensations": ["Компенсации и декомпенсации"],
    "material_cost": ["Себестоимость"],
}


ACCRUAL_COST_ROW_KEYS = [
    "sale_commission",
    "return_commission",
    "pickup_processing",
    "courier_departure",
    "dropoff_processing",
    "logistics",
    "reverse_logistics",
    "pickup_courier_delivery",
    "partner_returns_processing",
    "star_products",
    "temporary_partner_storage",
    "partner_dropoff_processing",
    "partner_packaging",
    "delivery_to_pickup",
    "acquiring",
    "cross_docking",
    "valid_preparation",
    "ozon_delivery_to_pvz",
    "warehouse_placement",
    "piece_acceptance",
    "zone_sorting",
    "excess_processing",
    "operational_errors",
    "temporary_sc_storage",
    "utilization",
    "packaging_materials",
    "penalty_non_recommended_slot",
    "loans_factoring",
    "other_accrual_adjustments",
    "shortage_retention",
]


AD_FINANCE_DESCRIPTIONS = {
    "оплата за клик",
    "закрепление отзыва",
    "реклама в сети интернет на сайте",
    "подписка premium",
    "подписка premium plus",
    "бонусы продавца - рассылка",
    "бонусы продавца",
    "баллы за отзывы",
    "вывод в топ",
    "спецразмещение",
    "продвижение с оплатой за заказ",
    "оплата за заказ",
}

DELIVERED_STATUSES = [
    "delivered",
    "доставлен",
    "доставляется",
    "ожидает в пвз",
    "у водителя",
    "ожидает отгрузки",
    "ожидает сборки",
]


PROMO_EVENT_ADDED = "ADDED"
PROMO_EVENT_REMOVED = "REMOVED"


PALLETIZATION_IMPORT_ARTICLE_COLUMNS = (
    "артикул",
    "offer_id",
    "offer id",
    "article",
    "sku",
)
PALLETIZATION_IMPORT_ITEMS_PER_LAYER_COLUMNS = (
    "сколько в один слой заходит",
    "штук в слое",
    "items_per_layer",
    "items per layer",
    "в один слой",
)

